### ISSUE TITLE
[mirror/question] ubuntun 18.04镜像站下载龟速

### ISSUE THREAD

**Issue by XianqiHe** [BITNP/issues#1]
#### 问题描述 (Question Description)

大部分文件都很快，秒下载，但每次都有个别的文件只有几百B/s的速度......国内外的源如阿里云、华为云、中科大都换过了，最后找到北理自家的源，问题还是没有解决，请问是哪里出了问题呢？

#### 相关地址 (Related URL)

libquadmath0、liblsan0一类的文件

#### 操作环境 (Environment)

[//]: # (请删除以下的括号以及其中的示例内容。Please remove the brackets and example text inside it below.)

 - OS: [ubuntun 18.04 LTS]
 - Software: [apt]

**Comment by phy25** [comment]
你好，感谢你的反馈。我们尝试在广州腾讯云复现此问题，未能复现，麻烦你能执行以下命令测试你提到的两个包的下载速度吗？

```shell
$ wget http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb
$ wget http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb
```

如果能提供 apt 的命令输出也能帮助我们排查问题。

此外你的网络环境是（网络提供商、有线/无线接入方式、speedtest 速度）？

```shell
root@qcloud:~# wget http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb
--2019-09-23 04:25:11--  http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb
Resolving mirror.bit.edu.cn (mirror.bit.edu.cn)... 114.247.56.117
Connecting to mirror.bit.edu.cn (mirror.bit.edu.cn)|114.247.56.117|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 133348 (130K) [application/octet-stream]
Saving to: ‘libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb’

libquadmath0_8.3.0-6ubun 100%[==================================>] 130.22K  --.-KB/s    in 0.1s

2019-09-23 04:25:12 (1.31 MB/s) - ‘libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb’ saved [133348/133348]

root@qcloud:~# wget http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb
--2019-09-23 04:26:14--  http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb
Resolving mirror.bit.edu.cn (mirror.bit.edu.cn)... 114.247.56.117, 2001:da8:204:1::22
Connecting to mirror.bit.edu.cn (mirror.bit.edu.cn)|114.247.56.117|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 132648 (130K) [application/octet-stream]
Saving to: ‘liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb’

liblsan0_8.3.0-6ubuntu1~ 100%[==================================>] 129.54K   855KB/s    in 0.2s

2019-09-23 04:26:15 (855 KB/s) - ‘liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb’ saved [132648/132648]
```

**Comment by XianqiHe** [comment]
感谢你的回复，这个问题是我在虚拟机上遇到的，后来我试着装双系统，问题消失了。应该是在虚拟机和windows之间的网络通讯没匹配好，不是源的问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Henry Pan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月23日(星期一) 凌晨4:32
收件人:&nbsp;"BITNP/issues"<issues@noreply.github.com&gt;;
抄送:&nbsp;"西格薯条"<2282214107@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BITNP/issues] [mirror/question] ubuntun 18.04镜像站下载龟速 (#1)




你好，感谢你的反馈。我们尝试在广州腾讯云复现此问题，未能复现，麻烦你能执行以下命令测试你提到的两个包的下载速度吗？
 $ wget http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb $ wget http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb
 
如果能提供 apt 的命令输出也能帮助我们排查问题。
 
此外你的网络环境是（网络提供商、有线/无线接入方式、speedtest 速度）？
 root@qcloud:~# wget http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb --2019-09-23 04:25:11--  http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb Resolving mirror.bit.edu.cn (mirror.bit.edu.cn)... 114.247.56.117 Connecting to mirror.bit.edu.cn (mirror.bit.edu.cn)|114.247.56.117|:80... connected. HTTP request sent, awaiting response... 200 OK Length: 133348 (130K) [application/octet-stream] Saving to: ‘libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb’ libquadmath0_8.3.0-6ubun 100%[==================================&gt;] 130.22K  --.-KB/s    in 0.1s 2019-09-23 04:25:12 (1.31 MB/s) - ‘libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb’ saved [133348/133348] root@qcloud:~# wget http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb --2019-09-23 04:26:14--  http://mirror.bit.edu.cn/ubuntu/pool/main/g/gcc-8/liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb Resolving mirror.bit.edu.cn (mirror.bit.edu.cn)... 114.247.56.117, 2001:da8:204:1::22 Connecting to mirror.bit.edu.cn (mirror.bit.edu.cn)|114.247.56.117|:80... connected. HTTP request sent, awaiting response... 200 OK Length: 132648 (130K) [application/octet-stream] Saving to: ‘liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb’ liblsan0_8.3.0-6ubuntu1~ 100%[==================================&gt;] 129.54K   855KB/s    in 0.2s 2019-09-23 04:26:15 (855 KB/s) - ‘liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb’ saved [132648/132648]
