### ISSUE TITLE
[mirror/question] 网站打开问题

### ISSUE THREAD

**Issue by ShadowPisFiend** [BITNP/issues#11]
#### 问题描述 (Question Description)

用家里的网络（非校园网环境）能正常打开mirror.bit.edu.cn，但是点安装matlab后就禁止校外访问，并且安装方法与授权密钥需要进入ca.bit.edu.cn，这两个就必须要校园网环境了。所以我使用easyconnect连接咱北理的vpn，但连接vpn后所有相关页面都打不开……作为对比，连vpn后可以登录教务处网站查询成绩课表什么的。所以想请问下是怎么回事儿呢？是easyconnect出问题了还是这两个网站出问题了

#### 相关地址 (Related URL)

mirror.bit.edu.cn
mirror.bit.edu.cn/matlab
ca.bit.edu.cn

#### 操作环境 (Environment)

 - OS: Windows 10

**Comment by phy25** [comment]
您好，学校 VPN 并不支持访问任意校内网站，VPN 连接状态下，对于不支持的校内网站会出现您描述的无法连接的现象。据我们网协所知，镜像站和校内正版软件平台均不在允许列表范围内。如对此有疑问，请联系校网络信息技术中心。

如镜像站页面提示所示，校园网外可直接在 MATLAB 官网下载。请使用北理工邮箱注册账号，即可自动获取校园授权、并在校园网外下载使用 MATLAB。如有疑问请评论回复。

**Comment by phy25** [comment]
更新：公网用户请访问 MATLAB 官网、使用北理工邮箱注册账户下载：https://www.mathworks.cn/licensecenter/licenses

**Comment by phy25** [comment]
我们重新测试了一下，VPN 似乎是可以打开正版化软件平台的，建议 Windows 用户使用 IE 浏览器访问相关网站。
