### ISSUE TITLE
mingwin64 文件名解释一下

### ISSUE THREAD

**Issue by anlexN** [BITNP/issues#19]
![image](https://user-images.githubusercontent.com/8686739/92856510-19fa7380-f426-11ea-9f61-6960db41ed30.png)

**Comment by phy25** [comment]
您好，请参见 https://github.com/ustclug/discussions/issues/340 和 https://github.com/tuna/issues/issues/965 ，这是 msys2 项目相关的文件。

由于我们网协并没有经常使用 msys2 的用户，如有疑问，建议您阅读 msys2 官方的相关文档说明并在官方的社区寻求帮助：https://www.msys2.org/docs/package-management/
