### ISSUE TITLE
[mirror/question] 能否将镜像站提交到Manjaro官方的镜像列表

### ISSUE THREAD

**Issue by shelfofclub** [BITNP/issues#21]
#### 问题描述 (Question Description)

能否提交到Manjaro官方的镜像列表，这样使用更加方便。

#### 相关地址 (Related URL)

[Manjaro Wiki](https://wiki.manjaro.org/index.php?title=Manjaro_Mirrors#Do_You_Manage_a_Potential_Manjaro_Mirror_Server.3F)

另，能否添加archlinuxcn镜像？（它的[镜像相关信息](https://github.com/archlinuxcn/mirrorlist-repo))

**Comment by phy25** [comment]
你好，我们暂时无法为官方带来的流量提供 SLA 保障，所以我们将会择期考虑此事宜。

关于新镜像的问题，请另外提交一个 issue：https://github.com/BITNP/issues/issues/new/choose

**Comment by shelfofclub** [comment]
@phy25 谢谢，期待后期的更新。

**Comment by phy25** [comment]
您好，由于策略变动本站将只支持 IPv6 访问，我们短期内将不会考虑扩展本站的访问渠道。再次感谢您的建议。
