### ISSUE TITLE
[mirror/repo] 希望增加PyPI的镜像

### ISSUE THREAD

**Issue by cdowen** [BITNP/issues#26]
#### 项目简介

The Python Package Index (PyPI) is a repository of software for the Python programming language.

PyPI helps you find and install software developed and shared by the Python community.

#### 上游地址与镜像方法

希望镜像的内容示例： 

[//]: # (请把下面的地址替换为任意一个或多个上游 URL 地址，或者下载页面的网址)

- https://pypi.tuna.tsinghua.edu.cn/simple
- https://pypi.org/

镜像方法：Python的文档中有关于建立Pypi镜像的部分，见：
- https://packaging.python.org/guides/index-mirrors-and-caches/

#### 其他信息

- 镜像大小：清华源中的数据是8.38TB
- 版权协议：Pypi中的packages包含各种开源版权协议，也有一部分没有给出版权协议

- 一些想法：Python在深度学习中有很多应用，但其实常用的包也只有那么些。不知道能不能建立一个cache，只缓存常用的包，这样mirror的数据量也许就没那么大。

**Comment by phy25** [comment]
PyPi 由于体积、内容、同步工具等原因，我们将不会在近年考虑增加。

我刚刚增加了一个 vote-welcome 的标签。在本 issue 的表态可能会被用于我们未来有机会重新评估请求的一个因素。

这个操作是我从 https://www.zachleat.com/web/eleventy-birthday/#close-all-feature-requests 抄来的。有机会的话我会试着写一些文档来把这个做法固定下来。
