### ISSUE TITLE
[mirror/status] 镜像站存储故障

### ISSUE THREAD

**Issue by phy25** [BITNP/issues#27]
由于镜像服务存储异常，目前北理工开源镜像站无法正常对内外网提供 HTTP、HTTPS、RSYNC 服务。我们正在等待有关部门的更多信息。

本 issue 将会同步更新镜像站服务监测状态。

**Comment by phy25** [comment]
有关部门老师正在处理故障中，我们正在协调将热点镜像的 HTTP 服务 302 跳转到其他镜像站的事宜（配置文件已准备就绪）。

**Comment by phy25** [comment]
目前已将以下热门镜像的 HTTP 服务 302 跳转至 mirrors.bfsu.edu.cn（校内 IPv4 用户会跳转至 mirrors6.bfsu.edu.cn 以确保不被计费，如您的校内网络没有 IPv6 连接，则您将暂时无法使用本站镜像服务）。如您有需要使用其它项目镜像，欢迎您在本 issue 留言，我们会尽快设置跳转。

```
/ubuntu/
/CTAN/
/apache/
/centos/
/deepin/
/deepin-cd/
/eclipse/
/qtproject/
/debian/
```

**Comment by everything411** [comment]
希望能够提供debian镜像的跳转，thanks

**Comment by Learner-ym** [comment]
希望能够提供KETTLE的镜像，thanks

**Comment by phy25** [comment]
@Learner-ym 您好，很抱歉我们不清楚国内的其它 KETTLE 镜像，且我们的镜像已经很长一段时间没有更新过（#17），建议您直接在 SourceForge 上更换镜像下载（https://sourceforge.net/projects/pentaho/ ），谢谢。

**Comment by phy25** [comment]
存储已在约 23 时恢复，我们正在恢复运行同步脚本，预计在 24 日早晨与有关部门确认后恢复镜像站对外服务。

**Comment by phy25** [comment]
站点已经恢复正常运行。
