### ISSUE TITLE
[request] 请求贵站加入 mirrorz.org

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [BITNP/issues#28]
最近开发一个项目 https://github.com/ZenithalHourlyRate/mirrorz ，目的是将各个镜像站的信息汇总起来，形成类似黄页的东西，不知道贵站是否有兴趣加入该项目

Demo: [www.mirrorz.org](https://www.mirrorz.org)

**Comment by phy25** [comment]
您好，感谢您提供的信息，由于本站点仍存在较多问题等待处理，我们会把处理本事宜的优先级放到最低（大约会在我们加入部分官方镜像时处理），敬请谅解。如本 issue 存在截止日期，您可直接关闭，谢谢。

对内备注：参见 https://github.com/tuna/mirrorz/blob/97ef2444f52040eba41b94200c911540f2077611/src/config/mirrors.js 目前 TUNA、USTC、SJTU、HIT 已加入这一站点。

**Comment by phy25** [comment]
您好，由于策略变动本站将只支持 IPv6 访问，我们短期内将不会考虑扩展本站的访问渠道。我们会考虑通过其它方式支持 MirrorZ 的发展。
