### ISSUE TITLE
[mirror/repo]希望能够引入manjaro的镜像及包管理同步

### ISSUE THREAD

**Issue by LaoshuBaby** [BITNP/issues#3]
#### 项目简介

Manjaro是一个基于arch linux的较新的一个Linux发行版，在各个发行版的排名和使用量上正飞速占据地位，逐渐成为一个用于桌面操作的发行版。为方便下载软件源，有必要对其进行同步。

#### 上游地址与镜像方法

希望镜像的内容示例： 

[//]: # (请把下面的地址替换为任意一个或多个上游 URL 地址，或者下载页面的网址)

- https://mirrors.tuna.tsinghua.edu.cn/manjaro/

镜像方法：如你知道更多如何完成镜像的信息，请在这里补充，否则请留空。

#### 其他信息

- 镜像大小：这怎么估计啊
- 版权协议：

**Comment by phy25** [comment]
版权协议：

- Free software licenses (mainly GPL) - https://en.wikipedia.org/wiki/Manjaro
- http://www.openinventionnetwork.com/joining-oin/oin-license-agreement/
  
  > The OIN license is a free, networked patent cross-license that provides licensees royalty-free access to all patents owned by OIN and provides a patent cross-license among the participants for certain Linux-related technologies known as the Linux System.
  > https://www.google.com/patents/licensing/#tab=oin

镜像大小：https://mirrors.tuna.tsinghua.edu.cn/status/

Name | Last Update | Upstream | Status | Size
-- | -- | -- | -- | --
manjaro | 2019-10-20 08:20 | rsync://mirror.yandex.ru/mirrors/manjaro/ | syncing | 99.65G
manjaro-cd | 2019-10-20 10:35 | rsync://mirrorservice.org/downloads.sourceforge.net/m/ma/manjarolinux/ | success | 6.77G

**Comment by phy25** [comment]
感谢建议！已经增加了有关资源。上面给到的 manjaro-cd 的资源地址是旧的，新的 manjaro-cd 托管在 OSDN。


名称 | 状态 | 大小 | 文件总数 | 来源
-- | -- | -- | -- | --
manjaro-cd | ✅  | 115.86 GB | 490 | rsync://ftp.iij.ad.jp/pub/osdn.jp/storage/g/m/ma/manjaro/
manjaro | ✅ | 85 GB | 197000 | rsync://mirrors.ocf.berkeley.edu/manjaro/
