### ISSUE TITLE
[mirror/repo] manjaro-cd 失效

### ISSUE THREAD

**Issue by phy25** [BITNP/issues#32]
#### 问题描述 (Question Description)

manjaro-cd 已经被迁移走了，似乎是迁移到了 GitHub，所以目前 OSDN 的同步基本上是在同步空内容。

我们不会考虑同步 daily build，我们要看看有没有稳定版 CD 的新同步渠道。

#### 相关地址 (Related URL)

See also https://github.com/tuna/issues/issues/1178

**Comment by phy25** [comment]
看了眼 https://github.com/manjaro/community-editions 的 CI，似乎他们之前是支持传到 OSDN、SF 跟 CDN77 的，但目前只有 CDN77 的配置。大概是可以考虑删掉了。

**Comment by everything411** [comment]
由于缺乏同步方式，我们决定移除manjaro-cd镜像。
