### ISSUE TITLE
[mirror/question] elpa 与 fedora-epel 同步故障

### ISSUE THREAD

**Issue by phy25** [BITNP/issues#34]
From @everything411:

> epel elpa 都是上游问题，上游不提供 rsync 了

名称 | 状态 | 大小 | 开始时间 | 完成时间 | 文件总数 | 更新量 | 来源
-- | -- | -- | -- | -- | -- | -- | --
elpa | ❌☕ 同步于 2021-Oct 18（有警告） | 10.37 GB | 2021-10-19 04:32:05+08:00 （尝试 4 次） | 13 分钟 | 52433 | 16.83 MB | rsync://elpa.emacs-china.org/elpa/
fedora-epel | ❌☕ 同步于 Mar 11（有警告） | 173.27 GB | 2022-03-12 00:52:01+08:00 （尝试 137 次） | 76 分钟 | 116233 | 18.68 GB | rsync://hkg.mirror.rackspace.com/epel/

**Comment by everything411** [comment]
目前
tuna的`elpa`上游为`rsync://elpa.gnu.org/elpa/`，`fedora-epel`上游为`rsync://download-ib01.fedoraproject.org/fedora-epel/`；
ustc的`elpa`上游为`rsync://mirrors.bfsu.edu.cn/elpa/`，`fedora-epel`上游为`rsync://mirrors.kernel.org/fedora-epel/`。

**Comment by everything411** [comment]
fedora-epel 上游已经恢复，然而gentoo又出现了问题，gentoo镜像的上游rsync://mirrors.kernel.org目前无法通过ipv6访问（ipv4 rsync正常）
```
$ rsync -6 -v rsync://mirrors.kernel.org
rsync: [Receiver] failed to connect to mirrors.kernel.org (2604:1380:45e3:2400::1): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(137) [Receiver=3.2.3]
```

**Comment by phy25** [comment]
目前这个 issue 只需要关注 elpa 的问题。

**Comment by everything411** [comment]
elpa同步上游修改为elpa.gnu.org
