### ISSUE TITLE
[mirror/question] 应当移除matlab的下载链接

### ISSUE THREAD

**Issue by cdowen** [BITNP/issues#36]
#### 问题描述 (Question Description)

应该移除matlab的下载链接，因为学校已不再提供matlab的安装方法与激活密钥。可以推荐octave，python等作为替代，需要的人也可以继续从极速之星等网站下载。

#### 相关地址 (Related URL)

URL: https://mirror.bit.edu.cn/matlab/

#### 操作环境 (Environment)

[//]: # (请删除以下的括号以及其中的示例内容。Please remove the brackets and example text inside it below.)

 - OS: win, mac os, linux
 - Software: matlab
 - Version: all

**Comment by phy25** [comment]
感谢反馈！我们一直以来不对校外提供 MATLAB 下载。我们会就此进行内部讨论。

**Comment by phy25** [comment]
我们已经移除了有关资源，感谢反馈！
