### ISSUE TITLE
[mirror/question] CentOS 6

### ISSUE THREAD

**Issue by 21ki** [BITNP/issues#37]
#### centos6 源(Question Description)

能否增加centos6的源，因为企业存在10年，里面还有很多都是centos6或者5，虽然官方不提供centos6的源但是是有归档的，国内我看阿里云和腾讯云都是由归档，地址如下

#### 相关地址 (Related URL)

腾讯云centos6 URL: https://mirrors.cloud.tencent.com/centos-vault/

腾讯云epel URL: https://mirrors.cloud.tencent.com/epel-archive/

阿里云centos6 URL: https://mirrors.aliyun.com/centos-vault/

阿里云epel URL: https://mirrors.aliyun.com/epel-archive/

**Comment by phy25** [comment]
您好，感谢您的建议。非常抱歉，由于资源问题，目前我们只会考虑校内的新需求。我们通常不会考虑普通企事业单位的需求，建议您继续使用相对支持此类用户较多的镜像服务。

此外，CentOS 官方已于 2020 年末停止支持 CentOS 6 版本，如果我们重新提供已不受官方支持的软件镜像，这不是在鼓励良好的信息安全实践，还请见谅。这类情况下，建议选用非官方提供的延长安全支持，此时应改用有关服务单位提供的软件包。
