### ISSUE TITLE
[mirror/status] 镜像服务网络故障

### ISSUE THREAD

**Issue by phy25** [BITNP/issues#38]
接监控提示，镜像 Web 服务从今日上午 10:12 开始无法从校内外访问。我们正在排查有关情况。

**Comment by BITNP-Public** [comment]
[自动回复]您好，我已收到您的邮件。感谢您的来信。

**Comment by phy25** [comment]
目前，我们初步判断系统故障为存储导致，我们正在尝试修复。

**Comment by phy25** [comment]
目前，我们正在等待有关部门对服务进行操作，我们预计故障修复耗时将比较长。

**Comment by phy25** [comment]
由于有关部门系统维护，镜像服务近几天将无法对外运行，预计下周前恢复。我们已经临时将服务切换到了维护模式。我们会在晚些时候对部分镜像配置跳转。

**Comment by phy25** [comment]
目前我们已将以下热门镜像的 HTTPS 服务 302 跳转至 mirrors.bfsu.edu.cn（校内 IPv4 用户会跳转至 mirrors6.bfsu.edu.cn 以确保不被计费，如您的校内网络没有 IPv6 连接，则您将暂时无法使用本站镜像服务）。如您有需要使用其它项目镜像，欢迎您在本 issue 留言，我们会尽快设置跳转。

```
/ubuntu/
/CTAN/
/apache/
/centos/
/deepin/
/deepin-cd/
/eclipse/
/qtproject/
/debian/
```

**Comment by phy25** [comment]
由于有关部门系统维护仍在继续，镜像服务停服时间将会延长若干天，敬请谅解。

**Comment by phy25** [comment]
有关部门系统维护已经结束，镜像服务已经恢复服务。
