### ISSUE TITLE
[mirror/status] 2022 年 8 月镜像服务维护公告

### ISSUE THREAD

**Issue by phy25** [BITNP/issues#39]
因学校系统维护，北理工开源镜像服务在 2022 年 8 月 1 日 8 时起，将无法对内外网提供服务，届时服务器可能会暂时失联。

我们预计会在当周晚些时候恢复服务，敬请谅解。

**Comment by everything411** [comment]
镜像服务已经切换至维护模式，我们将以下热门镜像的 HTTPS 服务 302 跳转至 mirrors.bfsu.edu.cn。在系统维护过程中北理开源镜像服务器可能会暂时失联，服务器失联期间 302 跳转功能无法生效。
```
/ubuntu/
/CTAN/
/apache/
/centos/
/deepin/
/deepin-cd/
/eclipse/
/qtproject/
/debian/
```

**Comment by phy25** [comment]
因我们需要更多时间与有关部门对接系统维护事项，我们将无法在本周恢复镜像服务，恢复时间未知，敬请谅解。

在此期间，我们将尽可能维持跳转功能正常运行。如需额外的镜像跳转，请您留言。

**Comment by everything411** [comment]
由于系统维护需要，近期北理开源镜像服务器会多次暂时失联，无法提供稳定的 302 跳转功能

**Comment by phy25** [comment]
我们预计会在本周末恢复正常镜像服务。

**Comment by phy25** [comment]
久等了！8 月上半月镜像服务配合学校系统维护的同时进行了系统升级，目前已经恢复服务。在此期间断服带来不便，还请谅解。
