### ISSUE TITLE
[mirror/question] 不能访问BIT mirrors /Couldn't access BIT mirrors

### ISSUE THREAD

**Issue by LaoshuBaby** [BITNP/issues#4]
#### 问题描述 (Question Description)
不能访问BIT mirrors
Couldn't access BIT mirrors
#### 相关地址 (Related URL)
全站
All URL about BIT mirrors

#### 操作环境 (Operation Environment)

 - OS:Windows 10 1903
 - Software: Firefox+Chrome+Edge
 - Version 最新版

 - OS:MIUI 10
 - Software: MIUI浏览器，via
 - Version 最新版

 - OS:CentOS　8
 - Software: yum

#### 网络环境 (Network Environment)

使用BUCT校园网（教育网，IPv6与IPv4均开放）不加载页面
默认使用IPv6，并且Ping不通

使用中国移动北京手机号效果如上
使用中国电信北京手机号效果如上

//群内BIT校内大佬反应手机流量在安卓端能够正常访问

**Comment by phy25** [comment]
你好，目前 mirror.bit.edu.cn 的 IPv6 服务异常且短时间内无法修复 #2，你能否尝试停用 IPv6 再试，或者：

```
$ curl -4 http://mirror.bit.edu.cn/
$ curl -6 http://mirror.bit.edu.cn/
```

**Comment by LaoshuBaby** [comment]
命令的执行结果均为
301 Moved Permanently
（Linux和Windows这个还是没区别的）
不过如果确实是IPv6的问题的话，在关闭之后确实可以使用
谢谢贵校贵协会运维人员的排查和努力！





------------------&nbsp;Original&nbsp;------------------

**Comment by phy25** [comment]
如果 `curl -4` 和 `curl -6` 返回结果一样的话应该 IPv6 能访问……？有点怪呢。

我们了解 IPv6 服务异常对镜像站双栈服务的影响，会导致这种访问不了的情况，还请谅解。

**Comment by LaoshuBaby** [comment]
那就不太清楚了……？_(:з」∠)_ 一开始校园网访问不通的时候其实是以为屏蔽了出校流量的……？ 但是最后确实是关掉v6以后能够正常访问，再次打开以后就不可以了 另： bit6的那个站点自始至终没能打开 —————————————————— 这就是全部情况吧……？_(:з」∠)_------------------ Original ------------------

**Comment by phy25** [comment]
您好，我们刚刚调整恢复了 IPv6 的服务，您可以再试一下看看是否恢复了。

**Comment by LaoshuBaby** [comment]
很谢谢贵校对于这方面需求的解决和关注，没有想到这么快就能够得到解决！
非常感谢！主站能够正常访问了！不过bit6的纯v6站点依然不能访问。（不过无所谓了）但是正常搜索bit镜像站的话搜到的主站是没问题的！
附上再一次curl的结果
![图片](https://user-images.githubusercontent.com/42690037/68954414-ec8d6b00-07fe-11ea-8022-c4380e7c4866.png)

**Comment by phy25** [comment]
感谢反馈！忘记说明了我们网络中心正在准备停用 *.bit6.edu.cn 这一域名，所以目前那边的解析是错误的。

https://github.com/BITNP/issues/issues/2#issuecomment-554459602

> 故障已修复。在进一步测试以及与网信中心协调后，网信中心老师以最快速度调整了新的 IP 段，恢复了 IPv6 正常服务。对故障期间给校外访问造成的不便，我代表网协深表歉意。
>
> 请留意，mirror.bit6.edu.cn 域名已停用，往后学校域名只提供双栈服务。
>
> 预估影响时长：53 天（24/Sep/2019:12:07:55 +0800 - 16/Nov/2019:13:30:00 +0800）
