### ISSUE TITLE
[mirror/repo] 希望增加PyPI和Ros1的镜像

### ISSUE THREAD

**Issue by RanFR** [BITNP/issues#43]
#### 申请增加Pypi和Ros1的镜像

The Robot Operating System (ROS) is a set of software libraries and tools that help you build robot applications. From drivers to state-of-the-art algorithms, and with powerful developer tools, ROS has what you need for your next robotics project. And it's all open source.

The Python Package Index (PyPI) is a repository of software for the Python programming language.

#### 上游地址与镜像方法

希望镜像的内容示例： 

[//]: # (请把下面的地址替换为任意一个或多个上游 URL 地址，或者下载页面的网址)

Pypi
- https://pypi.org/
- https://pypi.tuna.tsinghua.edu.cn/simple

Ros1
- http://packages.ros.org/ros/ubuntu/
- http://mirrors.ustc.edu.cn/ros/ubuntu/

python文档中有关于建立pypi的镜像方法
- https://packaging.python.org/guides/index-mirrors-and-caches/

Ros网站中也有建站说明
- http://wiki.ros.org/Mirrors#Creating_a_mirror

#### 其他信息

- 镜像大小：清华源的数据中，Pypi为18.2TB，ros1大小为97.2GB
- 版权协议：Pypi的packages中包含各种开源协议，也有一部分并未给出。Ros1遵循BSD-3开源协议。
- 北理工作为工科强校，不少老师和学生有使用ros和pypi的需求。希望学校能够在北理镜像站中加入对pypi和ros的支持！

**Comment by phy25** [comment]
与 #42 重复。如果您有额外的信息希望补充，还请在那个请求下评论。
