### ISSUE TITLE
[mirror/question] 希望增加两个单栈域名

### ISSUE THREAD

**Issue by lsylusiyao** [BITNP/issues#8]
#### 问题描述 (Question Description)

有的时候希望强制指定访问镜像站的通道是v4还是v6，希望可以添加mirror4.bit.edu.cn和mirror6.bit.edu.cn，以方便用户自行选择访问。

**Comment by phy25** [comment]
太久没搞国内备案这些的了，不知道现在把域名解析到不是自己的 IP 会不会有风险。我猜是没有。

方案 1（类 USTC）：

bitnet.mirrors.bitnp.net
ipv6.mirrors.bitnp.net
cernet.mirrors.bitnp.net - 202.204.80.77
chinanet.mirrors.bitnp.net - 219.143.204.117
unicom.mirrors.bitnp.net - 114.247.56.117

方案 2 （类 TUNA）：

mirrors4.bitnp.net - 202.204.80.77
mirrors6.bitnp.net - 2001:da8:204:1205::22

但远期来说，以后应该不需要 4/6 分线路的。

Update：正式加入这些域名之后还需要维护 TLS 证书。

**Comment by phy25** [comment]
https://mirrors4.bitnp.net, https://mirrors6.bitnp.net
