### ISSUE TITLE
[mirror/question] 希望更改域名名称

### ISSUE THREAD

**Issue by lsylusiyao** [BITNP/issues#9]
#### 问题描述 (Question Description)

国内高校镜像站如清华大学tuna（mirrors.tuna.tsinghua.edu.cn）、大连东软（mirrors.neusoft.edu.cn）和USTC（mirrors.ustc.edu.cn）均使用`mirrors`名称，而bit镜像站使用`mirror`，运维过程中经常忘记是否需要添加s。因此希望更改域名名称，将`mirror`改为`mirrors`

**Comment by phy25** [comment]
感谢建议！目前已经增加 https://mirrors.bit.edu.cn/ 的解析，但出于兼容问题，可能长时间内不会修改宣传的地址 mirror.bit.edu.cn。
